import { StyleSheet } from 'react-native';
import { colors } from './theme';

// Shared look for the newer feature screens (roommates, market, lease, wellbeing).
export const fs = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg, paddingTop: 12 },
  content: { padding: 16, gap: 12 },
  card: { backgroundColor: colors.card, borderRadius: 12, padding: 14, gap: 8 },
  cardTitle: { fontSize: 16, fontWeight: '700' },
  itemTitle: { fontSize: 15, fontWeight: '600' },
  lede: { fontSize: 13, color: colors.muted },
  body: { fontSize: 14, color: colors.body },
  meta: { fontSize: 12, color: colors.faint },
  bold: { fontWeight: '700' },
  empty: { color: colors.faint, textAlign: 'center', marginVertical: 8 },
  sectionHeading: { fontSize: 13, fontWeight: '700', color: colors.muted, marginTop: 4 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  flex: { flex: 1 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  field: { gap: 6 },
  label: { fontSize: 13, color: colors.muted },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 10, fontSize: 14 },
  textarea: { minHeight: 80, textAlignVertical: 'top' },
  chip: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 16, backgroundColor: colors.chip },
  chipOn: { backgroundColor: colors.accent },
  chipText: { fontSize: 13, color: colors.muted },
  chipTextOn: { fontSize: 13, color: '#fff', fontWeight: '600' },
  option: { padding: 12, borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.card },
  optionOn: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  box: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  boxOn: { backgroundColor: colors.accent, borderColor: colors.accent },
  tick: { color: '#fff', fontWeight: '800', fontSize: 12 },
  notice: { backgroundColor: colors.chip, color: colors.body, padding: 10, borderRadius: 8, overflow: 'hidden', fontSize: 13 },
  noticeOk: { backgroundColor: colors.accentSoft, color: colors.accent },
  noticeWarn: { backgroundColor: colors.warnSoft, color: colors.warn },
  noticeErr: { backgroundColor: '#fde7e5', color: colors.danger },
  badge: { fontSize: 11, fontWeight: '600', paddingVertical: 3, paddingHorizontal: 8, borderRadius: 10, overflow: 'hidden', alignSelf: 'flex-start', backgroundColor: colors.chip, color: colors.muted },
  badgeOk: { backgroundColor: colors.accentSoft, color: colors.accent },
  badgeWarn: { backgroundColor: colors.warnSoft, color: colors.warn },
  badgeBad: { backgroundColor: '#fde7e5', color: colors.danger },
  primary: { backgroundColor: colors.accent, borderRadius: 10, padding: 12, alignItems: 'center' },
  primarySmall: { backgroundColor: colors.accent, borderRadius: 16, paddingVertical: 7, paddingHorizontal: 14, alignSelf: 'flex-start' },
  primaryText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  ghost: { borderRadius: 16, paddingVertical: 7, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.border, alignSelf: 'flex-start' },
  ghostText: { color: colors.muted, fontWeight: '600', fontSize: 13 },
  danger: { borderRadius: 16, paddingVertical: 7, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.danger, alignSelf: 'flex-start' },
  dangerText: { color: colors.danger, fontWeight: '600', fontSize: 13 },
  kv: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  kvLabel: { fontSize: 14, color: colors.muted },
  kvValue: { fontSize: 14, fontWeight: '600', flexShrink: 1, textAlign: 'right' },
});
