import { defineSection } from './define';

export const booking = defineSection(
  {
    title: 'Booking',
    lede: 'Everything you can book for your apartment and building, in one place.',
    nothing: 'Nothing is set up for your apartment yet. Your building manager is adding the details, check back soon.',
    availableHeading: 'Available for your apartment',
    kinds: {
      laundry: { name: 'Laundry', blurb: '{n} machines, one-hour slots' },
      sauna: { name: 'Sauna', blurb: 'Two-hour turns, book alone or with a group' },
      parking: { name: 'Parking', blurb: '{n} spots, claim one for yourself' },
      common_room: { name: 'Common room', blurb: 'Meet, cook or celebrate together' },
      gym: { name: 'Gym', blurb: 'Reserve time to work out' },
      study_room: { name: 'Study room', blurb: 'A quiet room for you or a study group' },
      grill: { name: 'Grill and yard', blurb: 'Book the grill area with friends' },
    },
    spaceCount: '{n} to choose from',
    open: 'Open',
    invitesHeading: 'Invitations',
    invitedBy: 'invited you to',
    accept: 'Accept',
    decline: 'Decline',
    upcomingHeading: 'Your upcoming bookings',
    noUpcoming: 'You have nothing booked.',
    manage: 'Manage',
    organiser: 'Booked by',
    you: 'You',
    withCount: 'with {n} others',
    leave: 'Leave',
    cancel: 'Cancel booking',
    parkingHeld: 'Parking spot',
    // Slot pages
    today: 'Today',
    booked: 'Booked',
    free: 'Free',
    rulesSpace: 'Up to {perBooking} h per booking, {perWeek} h per week, {advance} days ahead. Open {open}-{close}.',
    capacity: 'Up to {n} people including you.',
    noSpaces: 'No spaces of this kind are set up for',
    backToBooking: 'All booking options',
    // Group panel
    panelHeading: 'Confirm your booking',
    pickHint: 'Choose a free time in the grid to start a booking.',
    selected: 'Selected',
    length: 'Length',
    hoursOption: '{n} h',
    note: 'Note (optional)',
    notePlaceholder: 'What is it for?',
    groupHeading: 'Book with others',
    groupLede: 'Leave everyone unticked to book just for yourself. People you add get an invitation.',
    inviteApartment: 'Invite everyone in my apartment',
    yourApartment: 'Your apartment',
    otherResidents: 'Other residents in your building',
    apartmentShort: 'Apt',
    confirm: 'Confirm booking',
    cancelPanel: 'Not now',
    groupOf: 'Group of {n}',
    // Errors
    errors: {
      invalidTime: 'That time is not valid.',
      past: 'That time has already passed.',
      tooFar: 'You can only book {n} days ahead.',
      notAvailable: 'That is not available for your apartment.',
      closed: 'That is outside the opening hours.',
      tooLong: 'That is longer than one booking may be.',
      weekly: 'You have used your {n} hours for that week.',
      taken: 'That time was just booked by someone else.',
      capacity: 'That is more people than fit ({n} at most).',
      outsider: 'You can only invite people from your own building.',
      notFound: 'Booking not found.',
    },
    pushInvite: 'You have been invited to a booking',
    // Staff
    staff: {
      title: 'Facilities and booking',
      lede: 'Choose what each building and apartment can book. Nothing is invented: a facility only shows up for residents once you have added it here.',
      building: 'Building',
      choose: 'Choose a building',
      amenitiesHeading: 'What this building offers',
      amenitiesLede: 'Automatic shows the option to residents when the building has something to book. Set it to No to hide it from the whole building.',
      auto: 'Automatic',
      yes: 'Yes',
      no: 'No',
      save: 'Save',
      inventoryHeading: 'Laundry, sauna and parking',
      addMachine: 'Add laundry machine',
      addSauna: 'Add sauna',
      addSpot: 'Add parking spot',
      labelPlaceholder: 'Label, for example Machine 3',
      add: 'Add',
      remove: 'Remove',
      saunaCapacity: 'People per turn',
      spacesHeading: 'Bookable spaces',
      spacesLede: 'Common rooms, gyms, study rooms and grill areas. Each has its own opening hours and limits.',
      noSpaces: 'No spaces added yet.',
      newSpace: 'Add a space',
      kind: 'Type',
      name: 'Name',
      description: 'Description',
      capacity: 'Capacity',
      opens: 'Opens (hour)',
      closes: 'Closes (hour)',
      perBooking: 'Max hours per booking',
      perWeek: 'Max hours per person per week',
      advance: 'Days ahead',
      delete: 'Delete space',
      unitsHeading: 'Apartment exceptions',
      unitsLede: 'Use this when one apartment differs from its building, for example an apartment with no sauna access. Leave it on Automatic otherwise.',
      unit: 'Apartment',
      noUnits: 'No apartments in this building yet.',
      bookingsHeading: 'Upcoming space bookings',
      noBookings: 'No upcoming space bookings.',
      cancelBooking: 'Cancel booking',
      inventoryNote: 'Removing a machine, sauna or spot also removes its bookings.',
      saved: 'Saved.',
    },
  },
  {
    title: 'Varaukset',
    lede: 'Kaikki, mitä voit varata asuntoosi ja taloosi, yhdessä paikassa.',
    nothing: 'Asuntoosi ei ole vielä lisätty mitään. Talon isännöitsijä lisää tiedot pian, katso myöhemmin uudelleen.',
    availableHeading: 'Asuntosi käytettävissä olevat',
    kinds: {
      laundry: { name: 'Pesutupa', blurb: '{n} konetta, tunnin vuorot' },
      sauna: { name: 'Sauna', blurb: 'Kahden tunnin vuorot, varaa yksin tai ryhmälle' },
      parking: { name: 'Pysäköinti', blurb: '{n} paikkaa, ota yksi itsellesi' },
      common_room: { name: 'Kerhohuone', blurb: 'Tapaa, kokkaa tai juhli yhdessä' },
      gym: { name: 'Kuntosali', blurb: 'Varaa aika treenaamiseen' },
      study_room: { name: 'Opiskeluhuone', blurb: 'Hiljainen huone yksin tai ryhmälle' },
      grill: { name: 'Grilli ja piha', blurb: 'Varaa grillauspaikka ystävien kanssa' },
    },
    spaceCount: '{n} vaihtoehtoa',
    open: 'Avaa',
    invitesHeading: 'Kutsut',
    invitedBy: 'kutsui sinut varaukseen',
    accept: 'Hyväksy',
    decline: 'Hylkää',
    upcomingHeading: 'Tulevat varauksesi',
    noUpcoming: 'Sinulla ei ole varauksia.',
    manage: 'Hallitse',
    organiser: 'Varaaja',
    you: 'Sinä',
    withCount: '{n} muun kanssa',
    leave: 'Poistu',
    cancel: 'Peru varaus',
    parkingHeld: 'Pysäköintipaikka',
    today: 'Tänään',
    booked: 'Varattu',
    free: 'Vapaa',
    rulesSpace: 'Enintään {perBooking} h per varaus, {perWeek} h viikossa, {advance} päivää eteenpäin. Auki {open}-{close}.',
    capacity: 'Enintään {n} henkilöä sinut mukaan lukien.',
    noSpaces: 'Tämän tyyppisiä tiloja ei ole lisätty kohteeseen',
    backToBooking: 'Kaikki varausvaihtoehdot',
    panelHeading: 'Vahvista varauksesi',
    pickHint: 'Valitse vapaa aika ruudukosta aloittaaksesi varauksen.',
    selected: 'Valittu',
    length: 'Kesto',
    hoursOption: '{n} h',
    note: 'Viesti (valinnainen)',
    notePlaceholder: 'Mihin tarvitset varauksen?',
    groupHeading: 'Varaa yhdessä muiden kanssa',
    groupLede: 'Jätä kaikki valitsematta, jos varaat vain itsellesi. Lisäämäsi henkilöt saavat kutsun.',
    inviteApartment: 'Kutsu kaikki asuntoni asukkaat',
    yourApartment: 'Asuntosi',
    otherResidents: 'Muut talosi asukkaat',
    apartmentShort: 'As.',
    confirm: 'Vahvista varaus',
    cancelPanel: 'Ei nyt',
    groupOf: '{n} hengen ryhmä',
    errors: {
      invalidTime: 'Aika ei kelpaa.',
      past: 'Aika on jo mennyt.',
      tooFar: 'Voit varata vain {n} päivää eteenpäin.',
      notAvailable: 'Tämä ei ole käytettävissä asunnossasi.',
      closed: 'Aika on aukioloaikojen ulkopuolella.',
      tooLong: 'Varaus on pidempi kuin sallittu.',
      weekly: 'Olet käyttänyt {n} tuntia kyseiselle viikolle.',
      taken: 'Joku ehti varata ajan juuri.',
      capacity: 'Henkilöitä on liikaa (enintään {n}).',
      outsider: 'Voit kutsua vain oman talosi asukkaita.',
      notFound: 'Varausta ei löytynyt.',
    },
    pushInvite: 'Sinut on kutsuttu varaukseen',
    staff: {
      title: 'Tilat ja varaukset',
      lede: 'Valitse, mitä kukin talo ja asunto voi varata. Mitään ei keksitä: tila näkyy asukkaille vasta, kun olet lisännyt sen tänne.',
      building: 'Talo',
      choose: 'Valitse talo',
      amenitiesHeading: 'Mitä talo tarjoaa',
      amenitiesLede: 'Automaattinen näyttää vaihtoehdon asukkaille, kun talossa on jotain varattavaa. Valitse Ei piilottaaksesi sen koko talolta.',
      auto: 'Automaattinen',
      yes: 'Kyllä',
      no: 'Ei',
      save: 'Tallenna',
      inventoryHeading: 'Pesutupa, sauna ja pysäköinti',
      addMachine: 'Lisää pesukone',
      addSauna: 'Lisää sauna',
      addSpot: 'Lisää pysäköintipaikka',
      labelPlaceholder: 'Nimi, esimerkiksi Kone 3',
      add: 'Lisää',
      remove: 'Poista',
      saunaCapacity: 'Henkilöitä per vuoro',
      spacesHeading: 'Varattavat tilat',
      spacesLede: 'Kerhohuoneet, kuntosalit, opiskeluhuoneet ja grillipaikat. Jokaisella on omat aukioloaikansa ja rajansa.',
      noSpaces: 'Tiloja ei ole vielä lisätty.',
      newSpace: 'Lisää tila',
      kind: 'Tyyppi',
      name: 'Nimi',
      description: 'Kuvaus',
      capacity: 'Kapasiteetti',
      opens: 'Aukeaa (tunti)',
      closes: 'Sulkeutuu (tunti)',
      perBooking: 'Tunteja per varaus enintään',
      perWeek: 'Tunteja per henkilö viikossa enintään',
      advance: 'Päiviä eteenpäin',
      delete: 'Poista tila',
      unitsHeading: 'Asuntokohtaiset poikkeukset',
      unitsLede: 'Käytä, kun yksi asunto poikkeaa talostaan, esimerkiksi asunto ilman saunan käyttöä. Muuten jätä Automaattinen.',
      unit: 'Asunto',
      noUnits: 'Tässä talossa ei ole vielä asuntoja.',
      bookingsHeading: 'Tulevat tilavaraukset',
      noBookings: 'Ei tulevia tilavarauksia.',
      cancelBooking: 'Peru varaus',
      inventoryNote: 'Koneen, saunan tai paikan poistaminen poistaa myös sen varaukset.',
      saved: 'Tallennettu.',
    },
  },
);
