import { defineSection } from './define';

export const household = defineSection(
  {
    title: 'Household',
    tabBills: 'Bills',
    tabChores: 'Chores',
    tabChat: 'Apartment board',
    noApartment: 'You need to be registered in an apartment to use this.',
    billsHeading: 'Split a bill',
    billsLede: 'Enter what the provider charged. Everyone you tick gets their exact share, and the cents always add up.',
    title_: 'What is it for',
    titlePlaceholder: 'Wi-Fi, September electricity',
    category: 'Type',
    categories: { wifi: 'Wi-Fi', electricity: 'Electricity', water: 'Water', other: 'Other' },
    total: 'Total (EUR)',
    paidBy: 'Paid by',
    dueDate: 'Due date (optional)',
    splitBetween: 'Split between',
    weight: 'Share weight',
    weightHint: 'Use 1 for everyone to split equally. Give someone 2 to make their share double, for example for a longer stay.',
    preview: 'Preview',
    saveBill: 'Save bill',
    openBills: 'Open bills',
    settledBills: 'Settled',
    noBills: 'No shared bills yet.',
    youPaid: 'You paid',
    paidByName: 'paid by',
    yourShare: 'Your share',
    owes: 'owes',
    markPaid: 'Mark paid',
    markUnpaid: 'Undo',
    paid: 'Paid',
    pending: 'Pending',
    delete: 'Delete',
    balanceHeading: 'Who owes what',
    allSettled: 'Everyone is settled up.',
    youOwe: 'You owe',
    owesYou: 'owes you',
    choresHeading: 'Chore rotation',
    choresLede: 'Each chore rotates through everyone in the apartment. Mark it done and the wheel moves on to the next person, who gets a push reminder when it is due.',
    newChore: 'Add a chore',
    choreName: 'Chore',
    choreNamePlaceholder: 'Take out the trash',
    every: 'Repeat every (days)',
    addChore: 'Add chore',
    noChores: 'No chores yet.',
    upNext: 'Up next',
    due: 'Due',
    overdue: 'Overdue',
    markDone: 'Done, pass it on',
    removeChore: 'Remove chore',
    days: 'days',
    you: 'You',
    boardHeading: 'Apartment board',
    boardLede: 'Your apartment chat is where everyone in the flat talks. It is moderated: any message can be reported, and Kuopas staff can remove it.',
    openChat: 'Open apartment chat',
    rules: 'House rules of the chat',
    rulesList: ['Be kind. No harassment, threats or slurs.', 'Keep private matters out of the chat.', 'Report anything that breaks these rules, staff will review it.'],
    members: 'People in your apartment',
    report: 'Report',
    reported: 'Reported',
    removedMessage: 'This message was removed by a moderator.',
  },
  {
    title: 'Kotitalous',
    tabBills: 'Laskut',
    tabChores: 'Askareet',
    tabChat: 'Asuntotaulu',
    noApartment: 'Sinun täytyy olla rekisteröitynyt asuntoon käyttääksesi tätä.',
    billsHeading: 'Jaa lasku',
    billsLede: 'Syötä laskun loppusumma. Jokainen merkitsemäsi saa tarkan osuutensa, ja sentit menevät aina tasan.',
    title_: 'Mihin lasku liittyy',
    titlePlaceholder: 'Wi-Fi, syyskuun sähkö',
    category: 'Tyyppi',
    categories: { wifi: 'Wi-Fi', electricity: 'Sähkö', water: 'Vesi', other: 'Muu' },
    total: 'Summa (EUR)',
    paidBy: 'Maksaja',
    dueDate: 'Eräpäivä (valinnainen)',
    splitBetween: 'Jaetaan kesken',
    weight: 'Osuuden paino',
    weightHint: 'Käytä 1 kaikille jakaaksesi tasan. Anna jollekulle 2 tuplataksesi hänen osuutensa, esimerkiksi pidemmän oleskelun takia.',
    preview: 'Esikatselu',
    saveBill: 'Tallenna lasku',
    openBills: 'Avoimet laskut',
    settledBills: 'Maksettu',
    noBills: 'Ei vielä jaettuja laskuja.',
    youPaid: 'Sinä maksoit',
    paidByName: 'maksaja',
    yourShare: 'Osuutesi',
    owes: 'on velkaa',
    markPaid: 'Merkitse maksetuksi',
    markUnpaid: 'Kumoa',
    paid: 'Maksettu',
    pending: 'Odottaa',
    delete: 'Poista',
    balanceHeading: 'Kuka on velkaa ja kenelle',
    allSettled: 'Kaikki on maksettu.',
    youOwe: 'Olet velkaa',
    owesYou: 'on velkaa sinulle',
    choresHeading: 'Askareiden kierto',
    choresLede: 'Jokainen askare kiertää kaikkien asunnon asukkaiden kesken. Merkitse tehdyksi, niin ratas siirtyy seuraavalle, joka saa push-muistutuksen eräpäivänä.',
    newChore: 'Lisää askare',
    choreName: 'Askare',
    choreNamePlaceholder: 'Vie roskat',
    every: 'Toistuu (päivää)',
    addChore: 'Lisää askare',
    noChores: 'Ei vielä askareita.',
    upNext: 'Vuorossa',
    due: 'Eräpäivä',
    overdue: 'Myöhässä',
    markDone: 'Tehty, siirrä eteenpäin',
    removeChore: 'Poista askare',
    days: 'päivää',
    you: 'Sinä',
    boardHeading: 'Asuntotaulu',
    boardLede: 'Asuntokeskustelu on paikka, jossa kaikki asunnon asukkaat keskustelevat. Sitä moderoidaan: mistä tahansa viestistä voi ilmoittaa, ja Kuopaksen henkilökunta voi poistaa sen.',
    openChat: 'Avaa asuntokeskustelu',
    rules: 'Keskustelun talon säännöt',
    rulesList: ['Ole ystävällinen. Ei häirintää, uhkailua tai solvauksia.', 'Pidä yksityiset asiat poissa keskustelusta.', 'Ilmianna kaikki, mikä rikkoo näitä sääntöjä, henkilökunta tarkistaa sen.'],
    members: 'Asuntosi asukkaat',
    report: 'Ilmianna',
    reported: 'Ilmiannettu',
    removedMessage: 'Moderaattori poisti tämän viestin.',
  },
);
