import { defineSection } from './define';

export const lease = defineSection(
  {
    title: 'Lease',
    tabLease: 'My lease',
    tabGuarantor: 'Guarantor',
    tabVerify: 'Verification',
    tabRoom: 'My room',
    noLease: 'You have no lease on record yet. Kuopas staff add it when your contract is confirmed.',
    active: 'Active',
    ended: 'Ended',
    cancelled: 'Cancelled',
    upcoming: 'Upcoming',
    kinds: {
      academic_9m: '9-month academic year',
      autumn: 'Autumn term',
      spring: 'Spring term',
      summer: 'Summer',
      rolling_12m: '12 months',
      custom: 'Custom term',
    },
    unit: 'Apartment',
    term: 'Term',
    rent: 'Monthly rent',
    deposit: 'Deposit',
    upfront: 'Rent required upfront',
    upfrontNone: 'None',
    months: 'months',
    daysLeft: 'days left',
    startsIn: 'days until move-in',
    schedule: 'Rent schedule',
    scheduleLede: 'The first and last months are prorated by the day when your term does not start or end on a month boundary.',
    period: 'Period',
    amount: 'Amount',
    due: 'Due',
    prorated: 'Prorated',
    paid: 'Paid',
    unpaid: 'Unpaid',
    total: 'Total',
    guarantorHeading: 'Guarantor',
    guarantorLede: 'International students often cannot provide a local guarantor. Choose a guarantor institution, or add a personal guarantor, and staff will review it.',
    guarantorStatus: 'Guarantor status',
    guarantorNone: 'No guarantor requested yet',
    guarantorApproved: 'Guarantor approved',
    guarantorPending: 'Guarantor under review',
    guarantorRejected: 'Guarantor rejected',
    institutions: 'Guarantor institutions',
    noInstitutions: 'No guarantor institutions have been set up yet. You can add a personal guarantor instead.',
    chooseInstitution: 'Use this institution',
    personalHeading: 'Personal guarantor',
    guarantorName: 'Guarantor name',
    guarantorEmail: 'Guarantor email',
    guarantorPhone: 'Guarantor phone',
    requestGuarantor: 'Request approval',
    requestSent: 'Sent. Staff will review it.',
    staffNote: 'Staff note',
    roomHeading: 'My room',
    roomLede: 'Photos and video tours of your apartment, and the people you will share it with.',
    noMedia: 'No photos or videos have been added for your apartment yet.',
    roommates: 'Your roommates',
    noRoommates: 'No roommates have registered in your apartment yet.',
    verifiedBadge: 'Verified',
  },
  {
    title: 'Vuokrasopimus',
    tabLease: 'Vuokrasopimukseni',
    tabGuarantor: 'Takaaja',
    tabVerify: 'Vahvistus',
    tabRoom: 'Huoneeni',
    noLease: 'Sinulla ei ole vielä vuokrasopimusta tiedoissa. Kuopaksen henkilökunta lisää sen, kun sopimuksesi on vahvistettu.',
    active: 'Voimassa',
    ended: 'Päättynyt',
    cancelled: 'Peruttu',
    upcoming: 'Tulossa',
    kinds: {
      academic_9m: '9 kuukauden lukuvuosi',
      autumn: 'Syyslukukausi',
      spring: 'Kevätlukukausi',
      summer: 'Kesä',
      rolling_12m: '12 kuukautta',
      custom: 'Oma jakso',
    },
    unit: 'Asunto',
    term: 'Jakso',
    rent: 'Kuukausivuokra',
    deposit: 'Vakuus',
    upfront: 'Ennakkoon maksettava vuokra',
    upfrontNone: 'Ei ole',
    months: 'kuukautta',
    daysLeft: 'päivää jäljellä',
    startsIn: 'päivää muuttoon',
    schedule: 'Vuokra-aikataulu',
    scheduleLede: 'Ensimmäinen ja viimeinen kuukausi lasketaan päiväkohtaisesti, jos jaksosi ei alu tai pääty kuukauden rajalla.',
    period: 'Jakso',
    amount: 'Summa',
    due: 'Eräpäivä',
    prorated: 'Päiväkohtainen',
    paid: 'Maksettu',
    unpaid: 'Maksamatta',
    total: 'Yhteensä',
    guarantorHeading: 'Takaaja',
    guarantorLede: 'Kansainvälisillä opiskelijoilla ei usein ole suomalaista takaajaa. Valitse takaajaorganisaatio tai lisää henkilökohtainen takaaja, ja henkilökunta tarkistaa sen.',
    guarantorStatus: 'Takaajan tila',
    guarantorNone: 'Takaajaa ei ole vielä pyydetty',
    guarantorApproved: 'Takaaja hyväksytty',
    guarantorPending: 'Takaaja tarkistettavana',
    guarantorRejected: 'Takaaja hylätty',
    institutions: 'Takaajaorganisaatiot',
    noInstitutions: 'Takaajaorganisaatioita ei ole vielä lisätty. Voit lisätä henkilökohtaisen takaajan.',
    chooseInstitution: 'Käytä tätä organisaatiota',
    personalHeading: 'Henkilökohtainen takaaja',
    guarantorName: 'Takaajan nimi',
    guarantorEmail: 'Takaajan sähköposti',
    guarantorPhone: 'Takaajan puhelin',
    requestGuarantor: 'Pyydä hyväksyntää',
    requestSent: 'Lähetetty. Henkilökunta tarkistaa sen.',
    staffNote: 'Henkilökunnan huomautus',
    roomHeading: 'Huoneeni',
    roomLede: 'Kuvia ja videokierroksia asunnostasi sekä ihmiset, joiden kanssa sen jaat.',
    noMedia: 'Asuntoosi ei ole vielä lisätty kuvia tai videoita.',
    roommates: 'Kämppäkaverisi',
    noRoommates: 'Asuntoosi ei ole vielä rekisteröitynyt kämppäkavereita.',
    verifiedBadge: 'Vahvistettu',
  },
);
