import { defineSection } from './define';

export const market = defineSection(
  {
    title: 'Market',
    tabBrowse: 'Browse',
    tabMine: 'My listings',
    tabNew: 'New listing',
    tabRequests: 'My requests',
    verifyFirst: 'The marketplace is only for verified residents, so every listing comes from a real student.',
    goVerify: 'Verify now',
    sublet: 'Sublet',
    swap: 'Room swap',
    all: 'All',
    empty: 'No listings here yet.',
    formHeading: 'List your room',
    formLede: 'Sublet your room for a term, or swap it with a resident in another apartment. Your own lease stays in place and staff approve every deal.',
    kind: 'What do you want to do',
    titleLabel: 'Title',
    titlePlaceholder: 'Room available for the summer',
    description: 'Describe the room',
    price: 'Monthly price (EUR)',
    from: 'Available from',
    to: 'Available until',
    wanted: 'What would you like in return',
    wantedPlaceholder: 'A room in Puijonlaakso, ground floor',
    publish: 'Publish listing',
    perMonth: 'per month',
    building: 'Apartment',
    floor: 'floor',
    wantsLabel: 'Looking for',
    request: 'Request',
    messageLabel: 'Message to the owner',
    messagePlaceholder: 'Introduce yourself and say why you are interested',
    sendRequest: 'Send request',
    requested: 'Request sent',
    yours: 'Your listing',
    status: {
      open: 'Open',
      pending_approval: 'Waiting for staff approval',
      completed: 'Completed',
      closed: 'Closed',
    },
    requestStatus: {
      pending: 'Pending',
      accepted: 'Accepted',
      declined: 'Declined',
      withdrawn: 'Withdrawn',
    },
    requestsHeading: 'Requests',
    noRequests: 'No requests yet.',
    accept: 'Accept',
    decline: 'Decline',
    close: 'Close listing',
    acceptedNote: 'You accepted a request. Kuopas staff will review the deal and confirm it.',
    withdraw: 'Withdraw',
    on: 'on',
    deals: 'Approved deals',
    subleaseDeal: 'Sublease approved',
    swapDeal: 'Swap approved',
  },
  {
    title: 'Kauppa',
    tabBrowse: 'Selaa',
    tabMine: 'Ilmoitukseni',
    tabNew: 'Uusi ilmoitus',
    tabRequests: 'Pyyntöni',
    verifyFirst: 'Kauppa on vain vahvistetuille asukkaille, joten jokainen ilmoitus on oikealta opiskelijalta.',
    goVerify: 'Vahvista nyt',
    sublet: 'Alivuokraus',
    swap: 'Huoneen vaihto',
    all: 'Kaikki',
    empty: 'Ei vielä ilmoituksia.',
    formHeading: 'Ilmoita huoneesi',
    formLede: 'Vuokraa huoneesi edelleen jaksoksi tai vaihda se toisen asunnon asukkaan kanssa. Oma sopimuksesi pysyy voimassa ja henkilökunta hyväksyy jokaisen sopimuksen.',
    kind: 'Mitä haluat tehdä',
    titleLabel: 'Otsikko',
    titlePlaceholder: 'Huone vapaana kesäksi',
    description: 'Kuvaile huonetta',
    price: 'Kuukausihinta (EUR)',
    from: 'Vapaana alkaen',
    to: 'Vapaana asti',
    wanted: 'Mitä haluat vastineeksi',
    wantedPlaceholder: 'Huone Puijonlaaksossa, maantasossa',
    publish: 'Julkaise ilmoitus',
    perMonth: 'kuukaudessa',
    building: 'Asunto',
    floor: 'kerros',
    wantsLabel: 'Etsii',
    request: 'Pyydä',
    messageLabel: 'Viesti omistajalle',
    messagePlaceholder: 'Esittele itsesi ja kerro, miksi olet kiinnostunut',
    sendRequest: 'Lähetä pyyntö',
    requested: 'Pyyntö lähetetty',
    yours: 'Sinun ilmoituksesi',
    status: {
      open: 'Avoin',
      pending_approval: 'Odottaa henkilökunnan hyväksyntää',
      completed: 'Valmis',
      closed: 'Suljettu',
    },
    requestStatus: {
      pending: 'Odottaa',
      accepted: 'Hyväksytty',
      declined: 'Hylätty',
      withdrawn: 'Peruttu',
    },
    requestsHeading: 'Pyynnöt',
    noRequests: 'Ei vielä pyyntöjä.',
    accept: 'Hyväksy',
    decline: 'Hylkää',
    close: 'Sulje ilmoitus',
    acceptedNote: 'Hyväksyit pyynnön. Kuopaksen henkilökunta tarkistaa sopimuksen ja vahvistaa sen.',
    withdraw: 'Peru',
    on: 'huoneessa',
    deals: 'Hyväksytyt sopimukset',
    subleaseDeal: 'Alivuokraus hyväksytty',
    swapDeal: 'Vaihto hyväksytty',
  },
);
