import { defineSection } from './define';

export const roommates = defineSection(
  {
    title: 'Roommates',
    tabFind: 'Matches',
    tabProfile: 'My profile',
    tabConnections: 'Connections',
    verifyFirst: 'Roommate matching is only for verified residents, so every profile is a real student.',
    goVerify: 'Verify now',
    noProfile: 'Answer a few questions about how you live and we will rank the people who fit you best.',
    startWizard: 'Start the questionnaire',
    editProfile: 'Edit my answers',
    wizardTitle: 'How do you live?',
    wizardLede: 'Answer honestly. Mark anything that is a dealbreaker for you and we will never match you with someone who is far apart on it.',
    step: 'Step',
    of: 'of',
    next: 'Next',
    back: 'Back',
    finish: 'Save my profile',
    nonNegotiable: 'This is non-negotiable for me',
    bioLabel: 'A few words about you',
    bioPlaceholder: 'Studying, hobbies, what a good home looks like to you',
    visibleLabel: 'Show my profile to other verified residents',
    finalStep: 'Almost done',
    saved: 'Profile saved.',
    matchesHeading: 'Your best matches',
    noMatches: 'No compatible verified residents yet. Check back as more people join.',
    hiddenNote: 'Your profile is hidden, so nobody can find you. Turn it on in My profile.',
    compatibility: 'compatible',
    matchesOn: 'Matches on',
    differsOn: 'Differs on',
    connect: 'Connect',
    requested: 'Request sent',
    accepted: 'Connected',
    message: 'Send a message',
    incoming: 'Requests for you',
    outgoing: 'Requests you sent',
    accept: 'Accept',
    decline: 'Decline',
    noConnections: 'No connections yet.',
    pending: 'Pending',
    declined: 'Declined',
    verifiedBadge: 'Verified',
    institution: 'Institution',
    dims: {
      sleepSchedule: 'Sleep schedule',
      cleanliness: 'Cleanliness',
      noiseTolerance: 'Noise',
      studyHabit: 'Studying',
      guestPolicy: 'Guests',
      smoking: 'Smoking',
      alcohol: 'Alcohol',
      cooking: 'Cooking',
    },
    questions: {
      sleepSchedule: {
        title: 'When do you usually sleep?',
        options: { early: 'Early, asleep before 22:00', regular: 'Regular, around midnight', late: 'Late, after 01:00' },
      },
      cleanliness: {
        title: 'How tidy do you keep shared spaces?',
        options: { '1': 'Relaxed', '2': 'A bit relaxed', '3': 'Average', '4': 'Tidy', '5': 'Spotless' },
      },
      noiseTolerance: {
        title: 'How much noise is fine at home?',
        options: { '1': 'I need quiet', '2': 'Mostly quiet', '3': 'Some noise is fine', '4': 'Lively', '5': 'The louder the better' },
      },
      studyHabit: {
        title: 'Where do you study?',
        options: { library: 'Mostly at the library', mixed: 'A mix', home: 'Mostly at home' },
      },
      guestPolicy: {
        title: 'How often do you have guests over?',
        options: { rarely: 'Rarely', sometimes: 'Sometimes', often: 'Often' },
      },
      smoking: {
        title: 'Smoking and vaping',
        options: { none: 'Not at home, no smoke', outside: 'Only outside', any: 'Fine with smoking' },
      },
      alcohol: {
        title: 'Alcohol at home',
        options: { none: 'None', social: 'Socially', often: 'Often' },
      },
      cooking: {
        title: 'How much do you cook?',
        options: { rarely: 'Rarely', sometimes: 'A few times a week', often: 'Every day' },
      },
    },
  },
  {
    title: 'Kämppäkaverit',
    tabFind: 'Osumat',
    tabProfile: 'Profiilini',
    tabConnections: 'Yhteydet',
    verifyFirst: 'Kämppäparin haku on vain vahvistetuille asukkaille, joten jokainen profiili on oikea opiskelija.',
    goVerify: 'Vahvista nyt',
    noProfile: 'Vastaa muutamaan kysymykseen elämäntavoistasi, niin järjestämme sinulle parhaiten sopivat ihmiset.',
    startWizard: 'Aloita kysely',
    editProfile: 'Muokkaa vastauksiani',
    wizardTitle: 'Miten elät?',
    wizardLede: 'Vastaa rehellisesti. Merkitse kaikki ehdottomat asiat, niin emme koskaan yhdistä sinua sellaiseen, joka on niissä kaukana sinusta.',
    step: 'Vaihe',
    of: '/',
    next: 'Seuraava',
    back: 'Takaisin',
    finish: 'Tallenna profiilini',
    nonNegotiable: 'Tämä on minulle ehdoton',
    bioLabel: 'Muutama sana sinusta',
    bioPlaceholder: 'Opiskelu, harrastukset, millainen on hyvä koti sinulle',
    visibleLabel: 'Näytä profiilini muille vahvistetuille asukkaille',
    finalStep: 'Melkein valmista',
    saved: 'Profiili tallennettu.',
    matchesHeading: 'Parhaat osumasi',
    noMatches: 'Ei vielä yhteensopivia vahvistettuja asukkaita. Tarkista myöhemmin uudelleen.',
    hiddenNote: 'Profiilisi on piilotettu, joten kukaan ei löydä sinua. Laita se päälle Profiilini-välilehdellä.',
    compatibility: 'sopii',
    matchesOn: 'Samaa mieltä',
    differsOn: 'Eroaa',
    connect: 'Ota yhteyttä',
    requested: 'Pyyntö lähetetty',
    accepted: 'Yhdistetty',
    message: 'Lähetä viesti',
    incoming: 'Sinulle tulleet pyynnöt',
    outgoing: 'Lähettämäsi pyynnöt',
    accept: 'Hyväksy',
    decline: 'Hylkää',
    noConnections: 'Ei vielä yhteyksiä.',
    pending: 'Odottaa',
    declined: 'Hylätty',
    verifiedBadge: 'Vahvistettu',
    institution: 'Oppilaitos',
    dims: {
      sleepSchedule: 'Unirytmi',
      cleanliness: 'Siisteys',
      noiseTolerance: 'Melu',
      studyHabit: 'Opiskelu',
      guestPolicy: 'Vieraat',
      smoking: 'Tupakointi',
      alcohol: 'Alkoholi',
      cooking: 'Ruoanlaitto',
    },
    questions: {
      sleepSchedule: {
        title: 'Milloin yleensä nukut?',
        options: { early: 'Aikaisin, nukkumassa ennen klo 22', regular: 'Tavallisesti, noin keskiyöllä', late: 'Myöhään, klo 01 jälkeen' },
      },
      cleanliness: {
        title: 'Kuinka siistinä pidät yhteiset tilat?',
        options: { '1': 'Rento', '2': 'Melko rento', '3': 'Keskiverto', '4': 'Siisti', '5': 'Priimasiisti' },
      },
      noiseTolerance: {
        title: 'Kuinka paljon melua kotona sopii?',
        options: { '1': 'Tarvitsen hiljaisuutta', '2': 'Enimmäkseen hiljaista', '3': 'Vähän melua sopii', '4': 'Vilkas', '5': 'Mitä kovempaa, sen parempi' },
      },
      studyHabit: {
        title: 'Missä opiskelet?',
        options: { library: 'Enimmäkseen kirjastossa', mixed: 'Vähän molemmissa', home: 'Enimmäkseen kotona' },
      },
      guestPolicy: {
        title: 'Kuinka usein sinulla on vieraita?',
        options: { rarely: 'Harvoin', sometimes: 'Joskus', often: 'Usein' },
      },
      smoking: {
        title: 'Tupakointi ja vaporointi',
        options: { none: 'Ei kotona, ei savua', outside: 'Vain ulkona', any: 'Tupakointi sopii' },
      },
      alcohol: {
        title: 'Alkoholi kotona',
        options: { none: 'Ei lainkaan', social: 'Seurassa', often: 'Usein' },
      },
      cooking: {
        title: 'Kuinka paljon kokkaat?',
        options: { rarely: 'Harvoin', sometimes: 'Muutaman kerran viikossa', often: 'Joka päivä' },
      },
    },
  },
);
