import { defineSection } from './define';

export const staff = defineSection(
  {
    nav: {
      verifications: 'Verify',
      guarantors: 'Guarantors',
      leases: 'Leases',
      maintenance: 'Insights',
      market: 'Market',
      wellbeing: 'Wellbeing',
      domains: 'Domains',
      facilities: 'Facilities',
    },
    maintenance: {
      title: 'Maintenance insights',
      lede: 'Recurring problems found automatically from resident reports: the same fault in the same apartment, floor, or vertical stack of apartments points to one physical cause.',
      related: 'Related',
      hotspots: 'Recurring problems (last 90 days)',
      noHotspots: 'No recurring problems detected.',
      stack: 'Vertical stack',
      floor: 'Floor',
      unit: 'Apartment',
      reports: 'reports',
      open: 'open',
      units: 'Apartments',
      latest: 'Latest',
      trend: 'Reports by type (last 90 days)',
      clusters: 'Open related tickets',
      noClusters: 'No related open tickets.',
      viewTicket: 'Open ticket',
      advice: {
        plumbing: 'Inspect the shared water riser and the drain stack for these apartments.',
        electrical: 'Check the distribution board and wiring feeding these apartments.',
        heating: 'Check the heating circuit, radiators and valves serving these apartments.',
        appliance: 'Check whether the same appliance model or supply is behind these faults.',
        pest: 'Plan a building-wide pest inspection and treatment.',
        noise: 'Look for a shared source such as ventilation, a lift, or neighbouring works.',
        structural: 'Have a surveyor check the structure around these apartments.',
        other: 'Review the reports together for a shared cause.',
      },
    },
    market: {
      title: 'Marketplace approvals',
      lede: 'Approve sublets and room swaps that residents have agreed between themselves. Approving a swap moves both residents to each other\'s apartment and updates their chats and leases.',
      empty: 'No deals waiting for approval.',
      sublet: 'Sublet',
      swap: 'Room swap',
      seller: 'Owner',
      requester: 'Other resident',
      dates: 'Dates',
      approve: 'Approve',
      reject: 'Reject',
      listings: 'Open listings',
      remove: 'Remove listing',
      noListings: 'No open listings.',
    },
    chatReports: {
      title: 'Reported chat messages',
      empty: 'No reported chat messages.',
      sender: 'Sender',
      reportedBy: 'Reported by',
      remove: 'Remove message',
      dismiss: 'Dismiss',
    },
    verifications: {
      title: 'Identity verifications',
      lede: 'Review uploaded IDs and proof of enrolment. The file is deleted as soon as you decide.',
      empty: 'No documents waiting for review.',
      view: 'View document',
      approve: 'Approve',
      reject: 'Reject',
      note: 'Note (optional)',
      institution: 'Institution',
      detail: 'Student number',
      resident: 'Resident',
    },
    guarantors: {
      title: 'Guarantors',
      lede: 'Approve guarantor requests and manage the guarantor institutions residents can choose from.',
      requests: 'Requests',
      empty: 'No pending guarantor requests.',
      personal: 'Personal guarantor',
      institutionKind: 'Institution',
      approve: 'Approve',
      reject: 'Reject',
      note: 'Note to the resident (optional)',
      institutions: 'Guarantor institutions',
      add: 'Add institution',
      name: 'Name',
      description: 'Description',
      url: 'Website (optional)',
      remove: 'Remove',
      none: 'No institutions yet.',
    },
    leases: {
      title: 'Leases',
      lede: 'Create term-based leases with automatic proration, manage academic terms, and plan the summer turnaround.',
      tabLeases: 'Leases',
      tabTerms: 'Academic terms',
      tabTurnaround: 'Turnaround',
      tabMedia: 'Unit media',
      newLease: 'New lease',
      resident: 'Resident',
      chooseResident: 'Choose a resident',
      type: 'Lease type',
      year: 'Start year',
      customDates: 'Custom dates (optional, override the preset)',
      start: 'Start',
      end: 'End',
      rent: 'Monthly rent (EUR)',
      deposit: 'Deposit (EUR)',
      upfront: 'Rent required upfront (months)',
      create: 'Create lease and rent schedule',
      existing: 'Existing leases',
      empty: 'No leases yet.',
      markEnded: 'Mark ended',
      cancel: 'Cancel lease',
      reopen: 'Reopen',
      charges: 'Charges',
      markPaid: 'Mark paid',
      markUnpaid: 'Mark unpaid',
      paid: 'Paid',
      termsHeading: 'Academic terms',
      termsLede: 'Terms define the calendar: when each term starts and ends, and when move-in is open.',
      termName: 'Name (for example Autumn 2026)',
      moveInFrom: 'Move-in opens',
      moveInTo: 'Move-in closes',
      addTerm: 'Add term',
      noTerms: 'No terms yet.',
      remove: 'Remove',
      turnaroundHeading: 'Turnaround planner',
      turnaroundLede: 'See every unit whose lease ends and every unit whose next lease starts in a window, and which units turn over on the same day.',
      from: 'From',
      to: 'To',
      show: 'Show',
      movingOut: 'Moving out',
      movingIn: 'Moving in',
      sameDay: 'Same-day turnarounds',
      vacant: 'Vacant gaps',
      noneInWindow: 'Nothing in this window.',
      building: 'Building',
      unit: 'Unit',
      date: 'Date',
      gap: 'Empty until',
      mediaHeading: 'Unit photos and video tours',
      mediaLede: 'Residents and matched roommates see these before moving in.',
      chooseUnit: 'Choose a unit',
      file: 'Photo or video',
      caption: 'Caption (optional)',
      upload: 'Upload',
      kinds: {
        academic_9m: '9-month academic year',
        autumn: 'Autumn term',
        spring: 'Spring term',
        summer: 'Summer',
        rolling_12m: '12 months',
        custom: 'Custom term',
      },
    },
  },
  {
    nav: {
      verifications: 'Vahvista',
      guarantors: 'Takaajat',
      leases: 'Vuokrat',
      maintenance: 'Analyysi',
      market: 'Kauppa',
      wellbeing: 'Hyvinvointi',
      domains: 'Verkkotunnukset',
      facilities: 'Tilat',
    },
    maintenance: {
      title: 'Kunnossapidon analyysi',
      lede: 'Asukkaiden ilmoituksista automaattisesti löytyvät toistuvat ongelmat: sama vika samassa asunnossa, kerroksessa tai asuntojen pystyrivissä viittaa yhteen fyysiseen syyhyn.',
      related: 'Liittyy',
      hotspots: 'Toistuvat ongelmat (viimeiset 90 päivää)',
      noHotspots: 'Toistuvia ongelmia ei havaittu.',
      stack: 'Pystyrivi',
      floor: 'Kerros',
      unit: 'Asunto',
      reports: 'ilmoitusta',
      open: 'avointa',
      units: 'Asunnot',
      latest: 'Viimeisin',
      trend: 'Ilmoitukset tyypeittäin (viimeiset 90 päivää)',
      clusters: 'Avoimet liittyvät tiketit',
      noClusters: 'Ei liittyviä avoimia tikettejä.',
      viewTicket: 'Avaa tiketti',
      advice: {
        plumbing: 'Tarkista näiden asuntojen yhteinen vesiputki ja viemäri.',
        electrical: 'Tarkista näitä asuntoja syöttävä sähkökeskus ja johdotus.',
        heating: 'Tarkista näitä asuntoja palveleva lämmityspiiri, patterit ja venttiilit.',
        appliance: 'Tarkista, onko vikojen takana sama laitemalli tai syöttö.',
        pest: 'Suunnittele koko talon tuholaistarkastus ja -torjunta.',
        noise: 'Etsi yhteinen lähde, kuten ilmanvaihto, hissi tai naapuruston työt.',
        structural: 'Teetä rakenteiden tarkastus näiden asuntojen ympäristössä.',
        other: 'Käy ilmoitukset läpi yhdessä yhteisen syyn löytämiseksi.',
      },
    },
    market: {
      title: 'Kaupan hyväksynnät',
      lede: 'Hyväksy alivuokraukset ja huoneenvaihdot, joista asukkaat ovat sopineet keskenään. Vaihdon hyväksyminen siirtää molemmat asukkaat toistensa asuntoon ja päivittää heidän keskustelunsa ja sopimuksensa.',
      empty: 'Ei hyväksyntää odottavia sopimuksia.',
      sublet: 'Alivuokraus',
      swap: 'Huoneen vaihto',
      seller: 'Omistaja',
      requester: 'Toinen asukas',
      dates: 'Päivät',
      approve: 'Hyväksy',
      reject: 'Hylkää',
      listings: 'Avoimet ilmoitukset',
      remove: 'Poista ilmoitus',
      noListings: 'Ei avoimia ilmoituksia.',
    },
    chatReports: {
      title: 'Ilmiannetut chat-viestit',
      empty: 'Ei ilmiannettuja chat-viestejä.',
      sender: 'Lähettäjä',
      reportedBy: 'Ilmiantaja',
      remove: 'Poista viesti',
      dismiss: 'Hylkää',
    },
    verifications: {
      title: 'Henkilöllisyyden vahvistukset',
      lede: 'Tarkista ladatut henkilöllisyystodistukset ja läsnäolotodistukset. Tiedosto poistetaan heti päätöksen jälkeen.',
      empty: 'Ei tarkistusta odottavia dokumentteja.',
      view: 'Näytä dokumentti',
      approve: 'Hyväksy',
      reject: 'Hylkää',
      note: 'Huomautus (valinnainen)',
      institution: 'Oppilaitos',
      detail: 'Opiskelijanumero',
      resident: 'Asukas',
    },
    guarantors: {
      title: 'Takaajat',
      lede: 'Hyväksy takaajapyyntöjä ja hallitse takaajaorganisaatioita, joista asukkaat voivat valita.',
      requests: 'Pyynnöt',
      empty: 'Ei odottavia takaajapyyntöjä.',
      personal: 'Henkilökohtainen takaaja',
      institutionKind: 'Organisaatio',
      approve: 'Hyväksy',
      reject: 'Hylkää',
      note: 'Viesti asukkaalle (valinnainen)',
      institutions: 'Takaajaorganisaatiot',
      add: 'Lisää organisaatio',
      name: 'Nimi',
      description: 'Kuvaus',
      url: 'Verkkosivu (valinnainen)',
      remove: 'Poista',
      none: 'Ei vielä organisaatioita.',
    },
    leases: {
      title: 'Vuokrasopimukset',
      lede: 'Luo jaksopohjaisia vuokrasopimuksia automaattisella päiväkohtaisella laskennalla, hallitse lukukausia ja suunnittele kesän vaihtuvuus.',
      tabLeases: 'Sopimukset',
      tabTerms: 'Lukukaudet',
      tabTurnaround: 'Vaihtuvuus',
      tabMedia: 'Asuntojen media',
      newLease: 'Uusi sopimus',
      resident: 'Asukas',
      chooseResident: 'Valitse asukas',
      type: 'Sopimustyyppi',
      year: 'Aloitusvuosi',
      customDates: 'Omat päivämäärät (valinnainen, ohittaa esiasetuksen)',
      start: 'Alkaa',
      end: 'Päättyy',
      rent: 'Kuukausivuokra (EUR)',
      deposit: 'Vakuus (EUR)',
      upfront: 'Ennakkoon maksettava vuokra (kuukautta)',
      create: 'Luo sopimus ja vuokra-aikataulu',
      existing: 'Olemassa olevat sopimukset',
      empty: 'Ei vielä sopimuksia.',
      markEnded: 'Merkitse päättyneeksi',
      cancel: 'Peru sopimus',
      reopen: 'Avaa uudelleen',
      charges: 'Maksut',
      markPaid: 'Merkitse maksetuksi',
      markUnpaid: 'Merkitse maksamattomaksi',
      paid: 'Maksettu',
      termsHeading: 'Lukukaudet',
      termsLede: 'Lukukaudet määrittävät kalenterin: milloin kausi alkaa ja päättyy ja milloin muutto on auki.',
      termName: 'Nimi (esimerkiksi Syksy 2026)',
      moveInFrom: 'Muutto alkaa',
      moveInTo: 'Muutto päättyy',
      addTerm: 'Lisää kausi',
      noTerms: 'Ei vielä kausia.',
      remove: 'Poista',
      turnaroundHeading: 'Vaihtuvuuden suunnittelija',
      turnaroundLede: 'Näe jokainen asunto, jonka sopimus päättyy, ja jokainen, jonka seuraava sopimus alkaa valitulla aikavälillä, sekä samana päivänä vaihtuvat asunnot.',
      from: 'Alkaen',
      to: 'Asti',
      show: 'Näytä',
      movingOut: 'Muuttaa pois',
      movingIn: 'Muuttaa sisään',
      sameDay: 'Samana päivänä vaihtuvat',
      vacant: 'Tyhjät jaksot',
      noneInWindow: 'Ei mitään tällä aikavälillä.',
      building: 'Rakennus',
      unit: 'Asunto',
      date: 'Päivä',
      gap: 'Tyhjänä asti',
      mediaHeading: 'Asuntojen kuvat ja videokierrokset',
      mediaLede: 'Asukkaat ja kämppäparit näkevät nämä ennen muuttoa.',
      chooseUnit: 'Valitse asunto',
      file: 'Kuva tai video',
      caption: 'Kuvateksti (valinnainen)',
      upload: 'Lataa',
      kinds: {
        academic_9m: '9 kuukauden lukuvuosi',
        autumn: 'Syyslukukausi',
        spring: 'Kevätlukukausi',
        summer: 'Kesä',
        rolling_12m: '12 kuukautta',
        custom: 'Oma jakso',
      },
    },
  },
);
