import { defineSection } from './define';

export const verify = defineSection(
  {
    tab: 'Verification',
    title: 'Verify your identity',
    lede: 'Roommate matching and the marketplace are only open to verified residents. It keeps scam listings and fake profiles out.',
    statusVerified: 'Verified',
    statusPending: 'Under review',
    statusNone: 'Not verified',
    verifiedVia: 'Verified through',
    methods: {
      university_email: 'University email',
      government_id: 'Government ID',
      enrollment_document: 'Proof of enrolment',
    },
    emailHeading: 'Verify with your university email',
    emailLede: 'We send a 6-digit code to your student email. It works instantly for recognised universities.',
    emailLabel: 'University email',
    sendCode: 'Send code',
    codeLabel: '6-digit code',
    confirm: 'Confirm',
    codeSent: 'Code sent. Check your inbox.',
    devCodeNote: 'Development mode, no email is sent. Your code is',
    codeWrong: 'That code is wrong or has expired.',
    notUniversity: 'That email is not from a recognised university.',
    cooldown: 'Please wait a minute before asking for another code.',
    emailUnavailable: 'Email sending is not set up yet. Use a document instead.',
    justVerified: 'You are verified.',
    docHeading: 'Or upload a document',
    docLede: 'Upload a government ID or proof of enrolment. Staff review it and the file is deleted as soon as they decide.',
    docType: 'Document type',
    institution: 'Institution (optional)',
    studentNumber: 'Student number (optional)',
    file: 'File (JPG, PNG, WebP or PDF)',
    submitDoc: 'Submit for review',
    docSubmitted: 'Submitted. Staff will review it soon.',
    docMissing: 'Choose a file to upload.',
    history: 'Your requests',
    rejected: 'Rejected',
    approved: 'Approved',
    pending: 'Pending',
    required: 'Verify your identity first to use this.',
    goVerify: 'Go to verification',
  },
  {
    tab: 'Vahvistus',
    title: 'Vahvista henkilöllisyytesi',
    lede: 'Kämppäparin haku ja markkinapaikka ovat vain vahvistetuille asukkaille. Näin huijausilmoitukset ja väärät profiilit pysyvät poissa.',
    statusVerified: 'Vahvistettu',
    statusPending: 'Tarkistettavana',
    statusNone: 'Ei vahvistettu',
    verifiedVia: 'Vahvistettu tavalla',
    methods: {
      university_email: 'Oppilaitoksen sähköposti',
      government_id: 'Viranomaisen myöntämä henkilöllisyystodistus',
      enrollment_document: 'Todistus läsnäolosta',
    },
    emailHeading: 'Vahvista oppilaitoksen sähköpostilla',
    emailLede: 'Lähetämme 6-numeroisen koodin opiskelijasähköpostiisi. Toimii heti tunnetuille oppilaitoksille.',
    emailLabel: 'Oppilaitoksen sähköposti',
    sendCode: 'Lähetä koodi',
    codeLabel: '6-numeroinen koodi',
    confirm: 'Vahvista',
    codeSent: 'Koodi lähetetty. Tarkista postilaatikkosi.',
    devCodeNote: 'Kehitystila, sähköpostia ei lähetetä. Koodisi on',
    codeWrong: 'Koodi on väärä tai vanhentunut.',
    notUniversity: 'Tämä sähköposti ei ole tunnetusta oppilaitoksesta.',
    cooldown: 'Odota hetki ennen uuden koodin pyytämistä.',
    emailUnavailable: 'Sähköpostin lähetystä ei ole vielä otettu käyttöön. Käytä dokumenttia.',
    justVerified: 'Olet vahvistettu.',
    docHeading: 'Tai lataa dokumentti',
    docLede: 'Lataa henkilöllisyystodistus tai todistus läsnäolosta. Henkilökunta tarkistaa sen ja tiedosto poistetaan heti päätöksen jälkeen.',
    docType: 'Dokumentin tyyppi',
    institution: 'Oppilaitos (valinnainen)',
    studentNumber: 'Opiskelijanumero (valinnainen)',
    file: 'Tiedosto (JPG, PNG, WebP tai PDF)',
    submitDoc: 'Lähetä tarkistettavaksi',
    docSubmitted: 'Lähetetty. Henkilökunta tarkistaa sen pian.',
    docMissing: 'Valitse ladattava tiedosto.',
    history: 'Pyyntösi',
    rejected: 'Hylätty',
    approved: 'Hyväksytty',
    pending: 'Odottaa',
    required: 'Vahvista ensin henkilöllisyytesi käyttääksesi tätä.',
    goVerify: 'Siirry vahvistukseen',
  },
);
