import { defineSection } from './define';

export const wellbeing = defineSection(
  {
    title: 'Wellbeing',
    emergency: 'In an emergency or if someone is in danger, call 112 now.',
    lede: 'Struggling with your mental health, money, or something else? Tell us and we can connect you with campus student support. You decide what is shared.',
    formHeading: 'I need support',
    category: 'What is it about',
    categories: {
      mental_health: 'Mental health',
      financial: 'Money or rent',
      behavioral: 'Behaviour or conflict',
      safety: 'Safety',
      other: 'Something else',
    },
    severity: 'How urgent is it',
    severities: { concern: 'I am concerned', urgent: 'This is urgent' },
    description: 'What is going on',
    descriptionPlaceholder: 'Share as much or as little as you like',
    consent: 'Kuopas may share this request and my contact details with the university student support service so they can reach out to me.',
    consentNote: 'If you do not tick this, Kuopas keeps it private and only follows up itself.',
    submit: 'Send request',
    sent: 'Your request was sent. A Kuopas manager will read it soon.',
    yourRequests: 'Your requests',
    none: 'You have not sent any requests.',
    status: {
      open: 'Received',
      acknowledged: 'Being handled',
      escalated: 'Shared with campus support',
      closed: 'Closed',
    },
    sharedWith: 'Shared with',
    close: 'Close this request',
    callTitle: 'Reach Kuopas directly',
    // Admin
    adminTitle: 'Wellbeing cases',
    adminLede: 'Sensitive. Only admins can see this page. Every action is recorded. Escalating shares a case with campus student support through the configured integration.',
    integrationOn: 'Campus support integration: connected',
    integrationOff: 'Campus support integration: not configured, escalations are recorded only. Set WELLBEING_WEBHOOK_URL to connect it.',
    open: 'Open cases',
    closedCases: 'Closed cases',
    noCases: 'No cases.',
    resident: 'Resident',
    consentYes: 'Resident agreed to share',
    consentNo: 'No consent to share',
    origin: { self: 'Raised by the resident', staff: 'Raised by staff' },
    acknowledge: 'Mark as being handled',
    note: 'Add a note',
    addNote: 'Save note',
    escalate: 'Escalate to campus student support',
    service: 'Service',
    servicePlaceholder: 'Campus student support',
    reason: 'Reason (required when the resident has not consented)',
    escalateButton: 'Escalate',
    closeCase: 'Close case',
    timeline: 'History',
    flagHeading: 'Flag a resident',
    flagLede: 'Raise a case yourself when you are worried about a resident. Sharing it without their consent needs a recorded reason.',
    chooseResident: 'Choose a resident',
    flag: 'Create case',
    needReason: 'A reason is required to share without consent.',
    escalatedOk: 'Escalated.',
    webhookResults: {
      sent: 'delivered to the integration',
      not_configured: 'recorded only, no integration configured',
      failed: 'the integration did not accept it',
    },
    actions: {
      created: 'Case created',
      acknowledged: 'Marked as being handled',
      note: 'Note',
      escalated: 'Escalated',
      closed: 'Closed',
    },
  },
  {
    title: 'Hyvinvointi',
    emergency: 'Hätätilanteessa tai jos joku on vaarassa, soita heti 112.',
    lede: 'Kamppailetko mielenterveyden, rahan tai jonkin muun kanssa? Kerro meille, niin voimme yhdistää sinut oppilaitoksen opiskelijatukeen. Sinä päätät, mitä jaetaan.',
    formHeading: 'Tarvitsen tukea',
    category: 'Mistä on kyse',
    categories: {
      mental_health: 'Mielenterveys',
      financial: 'Raha tai vuokra',
      behavioral: 'Käytös tai ristiriita',
      safety: 'Turvallisuus',
      other: 'Jokin muu',
    },
    severity: 'Kuinka kiireellinen',
    severities: { concern: 'Olen huolissani', urgent: 'Tämä on kiireellinen' },
    description: 'Mitä tapahtuu',
    descriptionPlaceholder: 'Kerro niin paljon tai vähän kuin haluat',
    consent: 'Kuopas saa jakaa tämän pyynnön ja yhteystietoni oppilaitoksen opiskelijatuelle, jotta he voivat ottaa minuun yhteyttä.',
    consentNote: 'Jos et valitse tätä, Kuopas pitää asian yksityisenä ja hoitaa jatkon itse.',
    submit: 'Lähetä pyyntö',
    sent: 'Pyyntösi lähetettiin. Kuopaksen päällikkö lukee sen pian.',
    yourRequests: 'Pyyntösi',
    none: 'Et ole lähettänyt pyyntöjä.',
    status: {
      open: 'Vastaanotettu',
      acknowledged: 'Käsittelyssä',
      escalated: 'Jaettu oppilaitoksen tuelle',
      closed: 'Suljettu',
    },
    sharedWith: 'Jaettu',
    close: 'Sulje tämä pyyntö',
    callTitle: 'Tavoita Kuopas suoraan',
    adminTitle: 'Hyvinvointitapaukset',
    adminLede: 'Arkaluonteista. Vain pääkäyttäjät näkevät tämän sivun. Jokainen toimi kirjataan. Eskalointi jakaa tapauksen oppilaitoksen opiskelijatuelle määritetyn integraation kautta.',
    integrationOn: 'Oppilaitoksen tuen integraatio: yhdistetty',
    integrationOff: 'Oppilaitoksen tuen integraatio: ei määritetty, eskaloinnit vain kirjataan. Yhdistä asettamalla WELLBEING_WEBHOOK_URL.',
    open: 'Avoimet tapaukset',
    closedCases: 'Suljetut tapaukset',
    noCases: 'Ei tapauksia.',
    resident: 'Asukas',
    consentYes: 'Asukas suostui jakamiseen',
    consentNo: 'Ei suostumusta jakamiseen',
    origin: { self: 'Asukkaan tekemä', staff: 'Henkilökunnan tekemä' },
    acknowledge: 'Merkitse käsittelyyn',
    note: 'Lisää muistiinpano',
    addNote: 'Tallenna muistiinpano',
    escalate: 'Eskaloi oppilaitoksen opiskelijatuelle',
    service: 'Palvelu',
    servicePlaceholder: 'Oppilaitoksen opiskelijatuki',
    reason: 'Perustelu (pakollinen, jos asukas ei ole suostunut)',
    escalateButton: 'Eskaloi',
    closeCase: 'Sulje tapaus',
    timeline: 'Historia',
    flagHeading: 'Nosta asukas esiin',
    flagLede: 'Luo tapaus itse, kun olet huolissasi asukkaasta. Jakaminen ilman suostumusta vaatii kirjatun perustelun.',
    chooseResident: 'Valitse asukas',
    flag: 'Luo tapaus',
    needReason: 'Jakaminen ilman suostumusta vaatii perustelun.',
    escalatedOk: 'Eskaloitu.',
    webhookResults: {
      sent: 'toimitettu integraatioon',
      not_configured: 'vain kirjattu, integraatiota ei ole määritetty',
      failed: 'integraatio ei hyväksynyt sitä',
    },
    actions: {
      created: 'Tapaus luotu',
      acknowledged: 'Merkitty käsittelyyn',
      note: 'Muistiinpano',
      escalated: 'Eskaloitu',
      closed: 'Suljettu',
    },
  },
);
